### ISSUE TITLE
load_all before linting causes lint error for RcppExports.R

### ISSUE THREAD

**Issue by jackwasey** [jimhester/lintr#84] opened 2015-04-14 11:31 UTC
Using an R session with working directory at the package (development tree) root, with my package loaded with `library`, or not loaded at all: lintr works fine. However, if I use `devtools::load_all()` before linting, I get:
`

> lintr::lint_package()
> ..............Error in get(fun, mode = "function", envir = parent.frame()) : 
>   object '.1' of mode 'function' was not found
> lint("R/RcppExports.R")
> Linting icd9..............Error in get(fun, mode = "function", envir = parent.frame()) : 
>   object '.1' of mode 'function' was not found
> `

In `.lintr` I have:
`linters: with_defaults(camel_case_linter = NULL, line_length_linter(120))`
`exclusions: list("R/RcppExports.R")`
(It seems that it is not excluded when running `lint_package`, but I'll be submitting this issue separately if so)

I don't see `.1` in RcppExports.R
The file itself can be found at: https://github.com/jackwasey/icd9/blob/rtf/R/RcppExports.R

using latest lintr :-)
`
 lintr          * 0.3.0.9001 2015-04-14 Github (jimhester/lintr@b34e1fd)
`

**Comment by paulhendricks** [comment] 2015-10-26 13:53
I would also like to report my experience with this bug. 

I'm using `lintr::expect_lint_free(exclusions = list("R/RcppExports.R)` in my unit tests. This test fails since RcppExports.R, an automagically generated file contains function arguments with single quotes instead of double quotes. 

Happy to re-submit this as a separate issue, but I felt it was best suited here.

**Comment by jackwasey** [comment] 2016-02-22 15:12
I've revisited this bug. It seems with CRAN version 0.3.3 it works fine, but with the latest github code a769c0b, I get the same error. It is very tricky even to see where it failed, with numerous stacked vapply functions, but it is definitely in RcppExports, and when codetools is called on it. Somehow codetools is being called with some nonsense code which doesn't exist in RcppExports.R

I'm afraid there are at least two problems here, perhaps worthy of more issues, which I'd be happy to file if you agree, or there is not a unifying fix:
 - opaque error when call to codetools fails
 - lintr calling codetools with nonsense code, which doesn't appear to be in the file in question (RcppExports.R)
 - not ignoring RcppExports.R when it is listed in exclusions (full path or just file name)

**Comment by jimhester** [comment] 2019-09-26 13:45
This is essentially a duplicate of #26 and is fixed by https://github.com/jimhester/lintr/commit/ecbd33bdeb8db559245d12494d148351e379e7c2

**Closed by jimhester** 2019-09-26 13:45 UTC
Labels: bug
