### ISSUE TITLE
Incomplete final line warning

### ISSUE THREAD

**Issue by md0u80c9** [jimhester/lintr#331] opened 2018-06-19 09:03 UTC
Hi,

If you don't leave a blank final line on the source file, you get an incomplete warning message from readLines:

```
> lintr::lint_package()
......................................................
Warning messages:
1: In readLines(filename) :
  incomplete final line found on '/Users/[REDACTED]/R/audit_measure.R'
2: In readLines(file) :
  incomplete final line found on '/Users/[REDACTED]/R/audit_measure.R'
> lintr::lint_package()
```

Given the output works fine if the trailing return is omitted, it would make more sense if this warning was suppressed, but instead a lintr message was generated (ie leave trailing carriage return on file is a lintr check).

**Comment by jimhester** [comment] 2019-09-27 19:30
This is a duplicate of #50

**Closed by jimhester** 2019-09-27 19:30 UTC
Labels: feature
