### ISSUE TITLE
Code inside `tryCatch()` `expr` argument causes error in linting

### ISSUE THREAD

**Issue by TARehman** [jimhester/lintr#393] opened 2019-08-09 17:35 UTC
I'm not sure if this is related to #84 - it seems like there may be some relationship, but it's not totally clear to me. Using `lintr 1.0.3` (and for what it's worth, `aws.s3 0.3.20`).

I have file.R consisting of this code:
```
tryCatch(
    expr = {
        library(aws.s3)
    },
    error = function(err) {
        install.packages(
            "aws.s3",
            repos = c("cloudyr" = "http://cloudyr.github.io/drat")
        )
    },
    finally = {
        library(aws.s3)
    }
)

```

I also have lint.R consisting of a simple command:
```
lintr::lint(filename = "file.R")

```

Running lint.R generates the following error message:
```
Error in get(fun, mode = "function", envir = parent.frame()) : 
  object 'aws.s3' of mode 'function' was not found
```

I did some exploration, and it turns out that whatever you put into the first argument (`expr`) seems to cause some issues. For instance, consider this version of file.R:
```
tryCatch(
    expr = {
        print("This is the expression")
    },
    error = function(err) {
        print("This is the error")
    },
    finally = {
        print("This is the end")
    }
)

```

Running the linter returns:
```
> lintr::lint(filename = "file.R")
[1] "This is the expression"
[1] "This is the end"
Error in get(fun, mode = "function", envir = parent.frame()) : 
  object 'This is the expression' of mode 'function' was not found
```

I'm not sure what's causing this. I do know that for a different package (`data.table`) there are no issues. If you put this in file.R, there are no problems.
```
tryCatch(
    expr = {
        library(data.table)
    },
    error = function(err) {
        install.packages("data.table")
    },
    finally = {
        library(data.table)
    }
)

```

**Comment by TARehman** [comment] 2019-08-10 03:14
I think this must have something to do with the way that objects are checked, because disabling object_usage_linter() causes it to stop happening.

**Comment by jimhester** [comment] 2019-09-26 13:45
This was a duplicate of #26 and is fixed by https://github.com/jimhester/lintr/commit/ecbd33bdeb8db559245d12494d148351e379e7c2

**Closed by jimhester** 2019-09-26 13:45 UTC
Labels: bug
