### ISSUE TITLE
Not reading config file

### ISSUE THREAD

**Issue by quartin** [jimhester/lintr#337] opened 2018-07-13 18:53 UTC
```
> library(lintr)
> lint(<filename>, parse_settings = TRUE)
> read.dcf(".lintr", all = TRUE)
                                                      linters    exclude
1 with_defaults(line_length_linter = line_length_linter(120)) "# nolint"
```
But I'm still getting:
![screen shot 2018-07-13 at 7 51 47 pm](https://user-images.githubusercontent.com/17933448/42708781-34791d16-86d6-11e8-8a83-f5d83a143004.png)

What am I missing here?

Session info: 
```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lintr_1.0.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16    packrat_0.4.8-1 digest_0.6.12   rprojroot_1.2   backports_1.1.1 magrittr_1.5    evaluate_0.10.1 stringi_1.1.7   lazyeval_0.2.1  rstudioapi_0.7 
[11] rex_1.1.2       rmarkdown_1.6   tools_3.5.0     stringr_1.3.0   igraph_1.2.1    yaml_2.1.18     compiler_3.5.0  pkgconfig_2.0.1 htmltools_0.3.6 knitr_1.20    
```

**Comment by pakuipers** [comment] 2018-07-27 13:22
Try without the equal sign:
line_length_linter(120)

**Comment by russHyde** [comment] 2019-09-19 10:24
I was interested in this since the syntax `with_defaults(line_length_linter = line_length_linter(120))` looked correct to me (that is, the equal sign in the `with_defaults` arguments should be allowed).

If anyone is getting an issue along these lines could they provide more detail about how their project is organised. I wrote a script to try to reproduce this issue and can't reproduce this with R3.5.1 and lintr=1.0.2 (or 1.0.3 or master).

My script looks like this:

```
mystery_func <- function() {
  linty.var.name <- 123
  linty.var.name * 2

  # 104 < line length < 120
  "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ"
}

setup_test_pkg <- function(name = "tempPackage", path = tempdir()) {
  pkg_path <- file.path(path, name)

  if (dir.exists(pkg_path)) {
    unlink(pkg_path, recursive = TRUE)
  }

  package.skeleton(name = name, list = "mystery_func", path = path)
}

test_linting <- function(pkg_path,
                         filename = "R/mystery_func.R") {
  old_path <- getwd()
  setwd(pkg_path)
  lints <- lint(filename = filename, parse_settings = TRUE)
  setwd(old_path)
  lints
}

###############################################################################

library(lintr)

d <- tempdir()
dir.create(d, showWarnings = FALSE)

message("*** linting using default .lintr setup ***")
setup_test_pkg("test1", d)
pkg_dir1 <- file.path(d, "test1")
print(test_linting(pkg_dir1))

message("*** linting using line_length <=120 ***")
setup_test_pkg("test2", d)
pkg_dir2 <- file.path(d, "test2")
cat(
  "linters: with_defaults(line_length_linter = line_length_linter(120))\n",
  file = file.path(pkg_dir2, ".lintr")
)
print(test_linting(pkg_dir2))
```

On sourcing the script a temporary package containing a single function script is setup, and that file is linted. lintr first uses default linters (line length <= 80) and then a .lintr-specified set of linters (lin length <= 120). The first, but not the second, run of lintr should throw a lint on line length and both should throw a lint on dotted.case varnames.

**Comment by russHyde** [comment] 2019-09-19 10:24
Flagged with reprex since a reproducible example is required

**Comment by jimhester** [comment] 2019-09-26 15:43
I think this is likely due to https://github.com/jimhester/lintr/issues/123

**Comment by jimhester** [comment] 2019-09-27 19:23
This is either a duplicate of #123 or not-reproducible, so I am closing this particular issue.

**Closed** 2019-09-27 19:22 UTC
Labels: reprex
